pipeline {
    agent any

    environment{
        GOPATH = "${WORKSPACE}/.go"
        GOCACHE = "${WORKSPACE}/.cache"
    }

    stages{
        stage('Unit Tests - Run Parallely'){
            parallel{
                stage('Unit Tests - Backend'){
                    agent{
                        docker{
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    steps{
                        dir('bugtracker-backend'){
                            sh 'go mod download'
                            //sh 'go test -v ./...'
                            //running unit test with go
                            sh 'go test ./... -v 2>&1 | go run github.com/jstemmer/go-junit-report/v2@latest > test-backend-results.xml'

                            //run test coverage for backend
                            sh 'go test -coverprofile=coverage.out -covermode=atomic ./...'
                            //convert that test coverage result to html file
                            sh 'go tool cover -html=coverage.out -o coverage.html'
                            sh 'mkdir -p reports'
                            sh 'mv coverage.html reports/coverage.html'
                        }
                    }
                    post{
                        always{
                            junit 'bugtracker-backend/test-backend-results.xml'
                            dir('bugtracker-backend'){
                                publishHTML(target: [
                                    reportDir: 'reports/', // Thư mục chứa file HTML
                                    reportFiles: 'coverage.html',
                                    reportName: 'Code Coverage Report - Backend' // Tên hiển thị trên menu Jenkins
                                ])
                            }
                        }
                    }
                }
                stage('Unit Tests - Frontend'){
                        agent{
                            docker{
                                image 'node:20-alpine'
                                reuseNode true
                            }
                        }
                        steps{
                            dir('bugtracker-frontend'){
                                sh '''
                                    npm ci
                                    npm test
                                '''
                            }
                        }
                        post{
                            always{
                                junit 'bugtracker-frontend/test-results.xml'
                                dir('bugtracker-frontend'){
                                    publishHTML(target: [
                                        reportDir: 'coverage/', // Thư mục chứa file HTML
                                        reportFiles: 'index.html',
                                        reportName: 'Code Coverage Report - Frontend' // Tên hiển thị trên menu Jenkins
                                    ])
                                }
                            }
                        }
                }
            }
        }
        stage('Launch application'){
            agent{
                docker{
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps{
                sh 'docker compose up --build -d'
                sh 'docker ps'
            }
        }
        stage('Mock Deploy'){
            steps{
                sh 'echo "Mocking deploy here"'
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}
