pipeline {
    agent any

    environment{
        GOPATH = "${WORKSPACE}/.go"
        GOCACHE = "${WORKSPACE}/.cache"
    }

    stages{
       stage('Unit Tests - Backend'){
            agent{
                docker{
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps{
                dir('bugtracker-backend'){
                    sh 'go mod download'
                    sh 'GOCACHE=off go test -v ./...'
                }
            }
       }
    }
}
