name: CI CD
on:
  push:
    branches: [main]

jobs:
  frontend-unit-test:
    name: Frontend - Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bugtracker-frontend
    container:
      image: node:24-alpine

    steps:
      - uses: actions/checkout@v4

      - name: npm ci
        run: npm ci
      - name: npm test
        run: npm test
      - name: Publish Junit Test Results
        if: always()
        run: junit 'bugtracker-frontend/test-results.xml'