name: CI CD
on:
  push:
    branches: [main]

jobs:
  frontend-unit-test:
    name: Frontend - Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bugtracker-frontend
    container:
      image: node:24-alpine
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: npm ci
        run: npm ci
      - name: npm test
        run: npm test
      - name: Publish Junit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Report Frontend - Unit Test result
          path: /test-results.xml
          retention-days: 3
      - name: Upload Code Coverage Frontend Report
        uses: actions/upload-artifact@v4
        with:
          name: Report Frontend - Coverage Code
          path: /coverage/index.html
          retention-days: 3