name: CI CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-unit-test:
    name: Frontend - Unit Test
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{steps.test-frontend.outputs.report}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node 24
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: bugtracker-frontend/package-lock.json

      - name: Running frontend unit test
        id: test-frontend
        working-directory: bugtracker-frontend
        run: |
          npm ci
          npm test
          npm test | tee full_output.txt
          echo 'FRONTEND COVERAGE REPORT```' >> $GITHUB_STEP_SUMMARY
          cat full_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```'

          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat full_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish Junit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Report Frontend - Unit Test Result
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit
      - name: Upload Code Coverage Frontend Report
        uses: actions/upload-artifact@v4
        with:
          name: Report Frontend - Coverage Code
          path: bugtracker-frontend/coverage/index.html
          retention-days: 3

  backend-unit-test:
    name: Backend - Unit Test
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{steps.test-backend.outputs.report}}
    defaults:
      run:
        working-directory: bugtracker-backend

    steps:
      - uses: actions/checkout@v4

      - name: go mod download
        run: go mod download

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Execute Backend Unit Test
        id: test-backend
        run: |
          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt
          echo "BACKEND COVERAGE REPORT" >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY

          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          go test -v ./... 2>&1 | $(go env GOPATH)/bin/go-junit-report > test-results.xml
      - name: hello here
        run: echo "hello here... hihi"
      - name: Publish Junit Test Result
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Reprot Backend - Unit Test Result
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit
      - name: Upload backend unit coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Report Backend - Coverage Code
          path: bugtracker-backend/coverage.html

  create-coverage-comment:
    if: github.event_name == 'pull_request'
    needs: [backend-unit-test, frontend-unit-test]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create Backend Coverage Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: |
            ## Backedn Test Coverage Report - Lin here
            ```
            ${{needs.backend-unit-test.outputs.coverage}}
            ```
      - name: Create Frontend Coverage Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: |
            ## Frontend Test Coverage Report - Lin here
            ```
            ${{needs.frontend-unit-test.outputs.coverage}}
            ```

  api-test:
    runs-on: ubuntu-latest
    needs: [frontend-unit-test, backend-unit-test]
    steps:
      - name: Checkout code from remote repo
        uses: actions/checkout@v4
      - name: Setup node 24
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Launch Servers Backend and Frontend
        run: docker compose up -d
      - name: Checking api/health
        run: npx wait-port http://localhost:8080/api/health -t 30000

      - name: npm ci
        run: npm ci
      - name: Run api test
        run: npx playwright test

      - name: Shut down Servers after done API testing
        run: docker compose down

      - name: Print working directory
        run: pwd

      - name: Upload API test result to github
        uses: actions/upload-artifact@v4
        with:
          name: 'APT Test Result'
          path: ./tests-api/test-results/

      - name: Upload HTML report to github
        uses: actions/upload-artifact@v4
        with:
          name: 'Playwright Report'
          path: ./tests-api/playwright-report/

      - name: Publish API test result to github
        uses: dorny/test-reporter@v1
        with:
          name: 'API Test Report Using Dorny action'
          path: ./tests-api/test-results/*.xml
          reporter: jest-junit